version: 2

jobs:
  lint:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/namespaces
  helmLint:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/namespaces

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
            - helmLint
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
